unqualified-search-registries = ["docker.io", "ghcr.io", "quay.io"]

[[registry]]
prefix = "docker.io"
location = "docker.io"
inseure = true

[[registry.mirror]]
location = "docker.m.daocloud.io"
[[registry.mirror]]
location = "docker.1ms.run"
[[registry.mirror]]
location = "docker.xuanyuan.me"

[[registry]]
prefix = "ghcr.io"
location = "ghcr.io"
inseure = true

[[registry.mirror]]
location = "ghcr.nju.edu.cn"

