version: "3.9"

networks:
  local_containers:
    external: true

services:
  bitwarden:
    container_name: vault
    image: vaultwarden/server:latest
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      DOMAIN: ${DOMAIN:-http://localhost:80}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED:-false}
      WEB_VAULT_ENABLED: ${WEBSOCKET_ENABLED:-true}
      WEBSOCKET_ENABLED: ${WEBSOCKET_ENABLED:-true}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      DATABASE_URL: ${DATABASE_URL:-/data/vaultwarden.db}
      LOG_FILE: ${LOG_FILE:-/data/vaultwarden.log}
    volumes:
      - ./data:/data:U,Z
    ports:
      - 0.0.0.0:1102:80
    networks:
      local_containers:
        ipv4_address: 10.25.11.2
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G
        reservations:
          cpus: 0.25
          memory: 256M
    logging:
      driver: k8s-file
      options:
        max-size: 10M
