version: "3.9"

networks:
  local_containers:
    external: true

services:
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:${SEARXNG_VERSION:-latest}
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      SEARXNG_SECRET: ${SEARXNG_SECRET}
      SEARXNG_HOST: ${SEARXNG_HOST:-0.0.0.0}
      SEARXNG_PORT: ${SEARXNG_PORT:-8888}
      SEARXNG_BASE_URL: ${SEARXNG_BASE_URL:-http://localhost:8888}
      SEARXNG_VALKEY_URL: ${SEARXNG_VALKEY_URL:-valkey://localhost:6379/0}
    volumes:
      - ./config/:/etc/searxng/:U,Z
      - ./caches/:/var/cache/searxng:U,Z
    ports:
      - 127.0.0.1:1109:8888
    networks:
      local_containers:
        ipv4_address: 10.25.11.9
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G
        reservations:
          cpus: 0.25
          memory: 256M
    logging:
      driver: k8s-file
      options:
        max-size: 10M

  mcp-searxng:
    container_name: mcp-searxng
    image: honbey/playground:26.8.8-mcp-searxng
    restart: unless-stopped
    depends_on:
      - searxng
    ports:
      - 127.0.0.1:1180:3000
    networks:
      local_containers:
        ipv4_address: 10.25.11.80
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M
        reservations:
          cpus: 0.1
          memory: 32M
    logging:
      driver: k8s-file
      options:
        max-size: 10M
