# /etc/fail2ban/jail.d/jail-sshd.conf
[DEFAULT]
ignoreip = 127.0.0.1/8 192.168.3.0/24
bantime = 86400
findtime = 600

[sshd]
enabled = true
port = 8989
filter = sshd
logpath = /var/log/secure
maxretry = 3
