version: "3.9"

networks:
  local_containers:
    external: true

services:
  valkey:
    container_name: valkey
    image: valkey/valkey:9-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    environment:
      _ADD_ENV_: ${_ADD_ENV_}
    volumes:
      - data:/data
    ports:
      - 127.0.0.1:1201:6379
    networks:
      local_containers:
        ipv4_address: 10.25.12.1
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G
        reservations:
          cpus: 0.25
          memory: 256M
    logging:
      driver: k8s-file
      options:
        max-size: 10M

volumes:
  data:
