version: "3.9"

networks:
  local_containers:
    external: true

services:
  code-server:
    container_name: code-server
    #image: codercom/code-server:latest
    image: honbey/playground:26.8.28-code-server
    restart: unless-stopped
    command:
      [
        "--auth=none",
        "--disable-update-check",
        "--disable-telemetry",
        "--link-protection-trusted-domains=*.freewisdom.cn",
        "--proxy-domain=code-{{port}}.freewisdom.cn:9090",
      ]
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      #VSCODE_PROXY_URI: ${VSCODE_PROXY_URI}
      DEFAULT_WORKSPACE: ${DEFAULT_WORKSPACE}
    volumes:
      - ./:/root:U,Z
      - ~/dotfiles:/root/dotfiles:U,Z
      - ~/workspace:/root/workspace:U,Z
      - ~/resources:/root/resources:U,Z
      - ~/.cargo:/root/.cargo:U,Z
      - ~/.rustup:/root/.rustup:U,Z
      - ~/.local/share/nvim/mason/packages:/root/.local/share/nvim/mason/packages:U,Z
      - /home/linuxbrew:/home/linuxbrew:U,Z
    ports:
      - 0.0.0.0:1103:8080
    networks:
      local_containers:
        ipv4_address: 10.25.11.3
    deploy:
      resources:
        limits:
          cpus: 6
          memory: 12G
        reservations:
          cpus: 0.25
          memory: 256M
    logging:
      driver: k8s-file
      options:
        max-size: 10M
