#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# Rime config preparation script
#
#   ./install.sh                # update all dicts + generate custom_phrase.txt
#   ./install.sh dicts [cn|en]  # update dicts only (cn or en only)
#   ./install.sh custom_phrase  # generate custom_phrase.txt only
#   ./install.sh export         # pack configs into rime-<timestamp>.tar.gz
#   ./install.sh -h             # show help
#
# Env vars:
#   RIME_ICE_BASE  Dict source URL prefix (default: GitHub raw of rime-ice main)
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

RIME_ICE_BASE="${RIME_ICE_BASE:-https://raw.githubusercontent.com/iDvel/rime-ice/refs/heads/main}"

# Colors for output (matching the style of the root install.sh)
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

function info() { echo -e "${GREEN}[INFO]${NC}  $*"; }
function err() { echo -e "${RED}[ERROR]${NC} $*"; }
function step() { echo -e "${CYAN}[STEP]${NC}  $*"; }

function usage() {
  cat <<EOF
Usage: $(basename "$0") [COMMAND]

Commands:
  dicts [cn|en]    Download/update dicts from rime-ice
  custom_phrase    Generate custom_phrase.txt (not tracked by git)
  export           Pack configs into rime-<timestamp>.tar.gz (no build dir)
  all              Run dicts then custom_phrase (default)
  -h, --help       Show this help

Env:
  RIME_ICE_BASE   Dict source URL prefix (default: GitHub raw of rime-ice main)

Examples:
  $(basename "$0")            # update all dicts
  $(basename "$0") dicts cn   # update Chinese dicts only
  RIME_ICE_BASE=https://ghproxy.com/... $(basename "$0")
EOF
}

# ---------- dict download ----------

# File list: only files maintained upstream by rime-ice; local custom/ext are untouched
CN_DICTS=(8105.dict.yaml base.dict.yaml others.dict.yaml)
EN_DICTS=(cn_en.txt en.dict.yaml en_ext.dict.yaml)

# Download a single file: fetch <subdir> <filename>
function fetch() {
  local dir="$1" file="$2"
  local url="${RIME_ICE_BASE}/${dir}/${file}"
  if curl -fsSL --connect-timeout 10 --max-time 300 --retry 3 --retry-delay 1 \
      -o "${dir}/${file}" "${url}" 2>/dev/null; then
    info "downloaded ${dir}/${file}"
  else
    err "failed: ${dir}/${file} (${url})"
    return 1
  fi
}

function update_dicts() {
  local scope="${1:-all}"
  command -v curl >/dev/null || { err "curl is required but not found."; exit 1; }
  mkdir -p cn_dicts en_dicts

  step "Downloading dicts from ${RIME_ICE_BASE}"
  local pids=() failed=0
  case "${scope}" in
    cn)
      for f in "${CN_DICTS[@]}"; do fetch cn_dicts "$f" & pids+=("$!"); done
      ;;
    en)
      for f in "${EN_DICTS[@]}"; do fetch en_dicts "$f" & pids+=("$!"); done
      ;;
    all)
      for f in "${CN_DICTS[@]}"; do fetch cn_dicts "$f" & pids+=("$!"); done
      for f in "${EN_DICTS[@]}"; do fetch en_dicts "$f" & pids+=("$!"); done
      ;;
    *)
      usage
      exit 1
      ;;
  esac

  # Wait for all downloads and aggregate failures; one failure does not abort the rest
  for p in "${pids[@]}"; do
    wait "$p" || failed=1
  done

  if ((failed)); then
    err "Some dicts failed to download. Please check network and retry."
    exit 1
  fi
  info "All dicts are up to date."
}

# ---------- custom_phrase generation ----------

# custom_phrase.txt is not tracked by git, so it does not exist after
# cloning; it is generated by this script.
# Note: entry lines must be Tab-separated (real Tabs in the heredoc)
# with LF line endings; do not mix in CR.
function gen_custom_phrase() {
  cat > custom_phrase.txt <<'EOF'
# Rime table
# coding: utf-8
#@/db_name	custom_phrase.txt
#@/db_type	tabledb
#
# version: "2026-08-03"
#
# no comment

Rime	rime	4
鼠须管	rime	3
https://rime.im/	rime	2
Squirrel	rime	1
EOF
  info "generated custom_phrase.txt"
}

# ---------- config export ----------

# Pack rime configs into rime-<timestamp>.tar.gz
# Exclude the build dir, .git and old archives
# Pack to a temp file first then move back, so tar never reads the
# archive itself (file changed as we read it)
function export_config() {
  local ts archive tmp_archive
  ts="$(date +%s)"
  archive="rime-${ts}.tar.gz"
  tmp_archive="$(mktemp)"
  tar -czf "${tmp_archive}" \
      --exclude='build' \
      --exclude='.git' \
      --exclude='*.tar.gz' \
      -C "${SCRIPT_DIR}" .
  mv "${tmp_archive}" "${SCRIPT_DIR}/${archive}"
  info "exported ${archive} ($(du -h "${archive}" | cut -f1))"
}

function main() {
  local cmd="${1:-all}"
  case "${cmd}" in
    dicts) update_dicts "${2:-all}" ;;
    custom_phrase) gen_custom_phrase ;;
    export) export_config ;;
    all)
      update_dicts "${2:-all}"
      gen_custom_phrase
      ;;
    -h|--help|help) usage ;;
    *)
      err "Unknown command: ${cmd}"
      usage
      exit 1
      ;;
  esac
}

main "$@"
