version: "3.9"

networks:
  local_containers:
    external: true

services:
  nanobot-1:
    image: honbey/nanobot:26.8.8-bd8d3ad5
    container_name: nanobot-1
    command:
      [
        "gateway",
        "--config",
        "/nanobot/config.json",
        "--workspace",
        "/nanobot/workspace",
      ]
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      NANOBOT_LLM_TIMEOUT_S: ${NANOBOT_LLM_TIMEOUT_S:-300}
      NANOBOT_OPENAI_COMPAT_TIMEOUT_S: ${NANOBOT_OPENAI_COMPAT_TIMEOUT_S:-300}
    volumes:
      - ./data:/nanobot:U,Z
    ports:
      - 127.0.0.1:1301:8765
    networks:
      local_containers:
        ipv4_address: 10.25.13.1
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
        reservations:
          cpus: 0.25
          memory: 256M
    logging:
      driver: k8s-file
      options:
        max-size: 10M
        path: ${HOME}/data/logs/containers/nanobot-1.log
