CREATE USER ntfy WITH PASSWORD '';

CREATE DATABASE ntfy
    ENCODING 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    TEMPLATE = template0
    OWNER = ntfy;

GRANT ALL PRIVILEGES ON DATABASE ntfy TO ntfy;
