version: "3.9"

networks:
  local_containers:
    external: true

services:
  ntfy:
    container_name: ntfy
    image: binwiederhier/ntfy:latest
    command:
      - serve
    restart: always
    environment:
    TZ: ${TZ:-Asia/Shanghai}
    NTFY_BASE_URL: ${NTFY_BASE_URL:-http://localhost:80}
    NTFY_BEHIND_PROXY: ${NTFY_BEHIND_PROXY:-true}
    NTFY_AUTH_FILE: ${NTFY_AUTH_FILE:-/etc/ntfy/auth.db}
    NTFY_CACHE_FILE: ${NTFY_CACHE_FILE:-/etc/ntfy/cache.db}
    NTFY_WEB_PUSH_FILE: ${NTFY_WEB_PUSH_FILE:-/etc/ntfy/web-push.db}
    # If use Postgres
    NTFY_DB_NAME: ${NTFY_DB_NAME}
    NTFY_DB_USER: ${NTFY_DB_USER}
    NTFY_DB_PASSWORD: ${NTFY_DB_PASSWORD}
    volumes:
      - ./config:/etc/ntfy:U,Z
      - ./attachments:/var/cache/ntfy/attachments:U,Z
    ports:
      - 0.0.0.0:1108:80
    networks:
      local_containers:
        ipv4_address: 10.25.11.8
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 512M
        reservations:
          cpus: 0.1
          memory: 32M
    logging:
      driver: k8s-file
      options:
        max-size: 10M
