version: "3.9"

networks:
  local_containers:
    external: true

services:
  grafana-alloy:
    container_name: grafana-alloy
    image: grafana/alloy:v1.19.0
    restart: unless-stopped
    command:
      [
        "run",
        "--server.http.listen-addr=0.0.0.0:3000",
        "--storage.path=/var/lib/alloy/data",
        "/etc/alloy/config.alloy",
      ]
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:U,Z
      - ${HOME}/app/web/nginx/logs:/logs/nginx:U,Z
    networks:
      local_containers:
        ipv4_address: 10.25.12.22
    ports:
      - 127.0.0.1:1222:3000
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1G
        reservations:
          cpus: 0.1
          memory: 16M
    logging:
      driver: k8s-file
      options:
        max-size: 10M

  grafana-loki:
    container_name: grafana-loki
    image: grafana/loki:3.7.6
    restart: unless-stopped
    command: ["-config.file=/etc/loki/config.yml", "-target=all"]
    #environment:
    volumes:
      - ./loki.yml:/etc/loki/config.yml:U,Z
      - ./loki-overrides.yml.yml:/etc/loki/overrides.yml:U,Z
      - ./loki:/loki:U,Z
    networks:
      local_containers:
        ipv4_address: 10.25.12.21
        aliases:
          - loki
    ports:
      - 127.0.0.1:1221:3100
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 4G
        reservations:
          cpus: 0.1
          memory: 16M
    logging:
      driver: k8s-file
      options:
        max-size: 10M

    healthcheck:
      test: ["CMD", "/usr/bin/loki", "-health"]
      start_period: 10s
      interval: 30s
      timeout: 5s
      retries: 3

  grafana:
    container_name: grafana
    image: grafana/grafana:13.2-slim
    restart: unless-stopped
    environment:
      GF_PATHS_PROVISIONING: ${GF_PATHS_PROVISIONING:-/etc/grafana/provisioning}
      GF_AUTH_ANONYMOUS_ENABLED: ${GF_AUTH_ANONYMOUS_ENABLED:-true}
      GF_AUTH_ANONYMOUS_ORG_ROLE: ${GF_AUTH_ANONYMOUS_ORG_ROLE:-Admin}
    depends_on:
      - grafana-loki
    volumes:
      - ./loki-grafana-ds.yml:/etc/grafana/provisioning/datasources/loki-ds.yml:U,Z
      - ./data:/var/lib/grafana:U,Z
    networks:
      local_containers:
        ipv4_address: 10.25.12.20
    ports:
      - 127.0.0.1:1220:3000
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G
        reservations:
          cpus: 0.25
          memory: 128M
    logging:
      driver: k8s-file
      options:
        max-size: 10M

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
