version: "3.9"

networks:
  local_containers:
    external: true

services:
  anki-sync:
    image: anki-sync:26.7.25
    container_name: anki-sync
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/data:U,Z
    ports:
      - 0.0.0.0:1105:8080
    networks:
      local_containers:
        ipv4_address: 10.25.11.5
    logging:
      driver: k8s-file
      options:
        max-size: "10M"
