version: "3.9"

networks:
  local_containers:
    external: true

services:
  postgres:
    container_name: postgres
    image: docker.io/library/postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-data}
    volumes:
      - data:/var/lib/postgresql
      # Postgres 17
      #- data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:1202:5432
    networks:
      local_containers:
        ipv4_address: 10.25.12.2
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G
        reservations:
          cpus: 0.25
          memory: 256M
    logging:
      driver: k8s-file
      options:
        max-size: 10M

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 60s
      timeout: 3s
      retries: 3

volumes:
  data:
