version: "3.9"

networks:
  local_containers:
    external: true

services:
  dufs:
    container_name: dufs
    image: sigoden/dufs:latest
    command:
      #/data -A -a ${ADMIN}@/:rw -a ${SYNC1}@/sync:rw -a ${USER1}@/tmp:rw -a @/public
      ["/data", "-A", "-a", "@/:rw"]
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      #ADMIN: ${ADMIN}
      #SYNC1: ${SYNC1}
      #USER1: ${USER1}
    volumes:
      - ./data:/data
    ports:
      - 0.0.0.0:1104:5000
    networks:
      local_containers:
        ipv4_address: 10.25.11.4
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
        reservations:
          cpus: 0.1
          memory: 16M
    logging:
      driver: k8s-file
      options:
        max-size: 10M
